import type { GoesProduct, GoesProductCategory } from '../types/goes';

export const MARANHAO_BBOX = {
  minLon: -48.9,
  maxLon: -41.7,
  minLat: -10.6,
  maxLat: -1.0,
};

export const CATEGORY_LABELS: Record<GoesProductCategory | 'todos', string> = {
  todos: 'Todos',
  nuvens: 'Nuvens',
  vapor_agua: "Vapor d'agua",
  raios: 'Raios',
  chuva: 'Chuva',
  topo_nuvem: 'Topo de nuvem',
  focos_calor: 'Focos de calor',
  boletim: 'Boletim',
};

export const SOURCE_LABELS: Record<GoesProduct['source'], string> = {
  NOAA_GOES_IMAGE_VIEWER: 'NOAA GOES Image Viewer',
  NOAA_AWS: 'NOAA Open Data AWS',
  NASA_WORLDVIEW: 'NASA Worldview',
  NOAA_CLASS_AIRS: 'NOAA NCEI CLASS/AIRS',
};

export const goesCatalog: GoesProduct[] = [
  {
    id: 'geocolor-nuvens',
    title: 'GeoColor / Nuvens',
    category: 'nuvens',
    source: 'NOAA_GOES_IMAGE_VIEWER',
    satellite: 'GOES-19',
    viewerUrl: 'https://www.star.nesdis.noaa.gov/goes/sector.php?sat=G19&sector=taw',
    description: 'Imagem visual composta para acompanhamento de nebulosidade, organização convectiva e cobertura de nuvens.',
    technicalUse: 'Visao geral de nebulosidade e apoio visual ao boletim.',
    bulletinUse: 'Ilustrar condicoes de nuvens e sistemas meteorologicos atuantes.',
    limitations: 'Produto visual de apoio, sem estimativa quantitativa direta de chuva ou severidade.',
  },
  {
    id: 'glm-flash-extent-density',
    title: 'GLM Flash Extent Density / Raios',
    category: 'raios',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'GLM-L2-LCFA',
    description: 'Produto GLM para atividade eletrica atmosferica detectada pelo satelite GOES-R.',
    technicalUse: 'Acompanhar densidade e extensao de flashes em areas convectivas.',
    bulletinUse: 'Indicar atividade eletrica atmosferica associada a tempestades.',
    limitations: 'Nao substitui rede local de deteccao de descargas e pode exigir agregacao temporal para analise operacional.',
  },
  {
    id: 'abi-vapor-agua',
    title: "Vapor d'agua ABI",
    category: 'vapor_agua',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'ABI-L2-MCMIPF',
    viewerUrl: 'https://www.star.nesdis.noaa.gov/goes/sector_band.php?sat=G19&sector=taw&band=09',
    description: 'Produtos relacionados as bandas ABI 8, 9 e 10 e composicoes MCMIPF para analise de umidade em niveis medios e altos.',
    technicalUse: 'Analisar umidade atmosferica, subsidencia, cavados e organizacao de sistemas.',
    bulletinUse: 'Contextualizar disponibilidade de umidade e suporte dinamico para conveccao.',
    limitations: 'Interpreta umidade em camadas atmosfericas e nao representa umidade de superficie ou solo.',
  },
  {
    id: 'cloud-top-temperature',
    title: 'Temperatura de topo de nuvem',
    category: 'topo_nuvem',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'ABI-L2-ACHTF',
    description: 'Produto ABI para caracterizacao de altura e temperatura de topo de nuvens em disco completo.',
    technicalUse: 'Identificacao de nuvens frias/altas e conveccao.',
    bulletinUse: 'Apoiar descricao de nucleos convectivos e potencial de tempo significativo.',
    limitations: 'Nao mede chuva diretamente e depende de interpretacao junto a outros produtos.',
  },
  {
    id: 'rrqpe-chuva-estimada',
    title: 'Chuva estimada / RRQPE',
    category: 'chuva',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'ABI-L2-RRQPEF',
    description: 'Estimativa instantanea de taxa de precipitacao derivada do ABI para disco completo.',
    technicalUse: 'Estimativa instantanea de taxa de precipitacao por pixel.',
    bulletinUse: 'Sinalizar areas com precipitacao estimada e suporte a analise agrometeorologica.',
    limitations: 'Estimativa indireta por satelite, sujeita a vieses e validacao local obrigatoria.',
  },
  {
    id: 'focos-calor-fdc',
    title: 'Focos de calor',
    category: 'focos_calor',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'ABI-L2-FDCF',
    description: 'Produto Fire Detection and Characterization para deteccao de hotspots em disco completo.',
    technicalUse: 'Monitorar hotspots e apoiar alertas ambientais.',
    bulletinUse: 'Informar possiveis focos de calor relevantes para o boletim ambiental.',
    limitations: 'Deteccoes podem ser afetadas por nuvens, angulo de visada e resolucao espacial.',
  },
  {
    id: 'imagem-multicanal-mcmipf',
    title: 'Imagem multicanal',
    category: 'boletim',
    source: 'NOAA_AWS',
    satellite: 'GOES-19',
    awsBucket: 'noaa-goes19',
    awsProductPrefix: 'ABI-L2-MCMIPF',
    description: 'Arquivo multicanal ABI em disco completo para composicoes visuais e produtos derivados.',
    technicalUse: 'Base multicanal para composicao visual e triagem de produtos ambientais.',
    bulletinUse: 'Composicao visual para boletins e imagens de apoio.',
    limitations: 'Arquivos NetCDF devem ser processados no backend ou pipeline dedicado, nao no frontend.',
  },
];
